# Generated by Django 5.0 on 2023-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name="Post's text")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
