# Generated by Django 5.0 on 2023-12-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customusermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='last_request',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Request'),
        ),
    ]
